export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  COURSES: "/courses",
  DASHBOARD: "dashboard",
  PROFILE: "profile",
  ANALYTICS: "analytics",
  ASSIGNMENTS: "assignments",
  LIVE_SESSIONS: "live-sessions",
  SETTINGS: "settings",
  ADMIN: {
    DASHBOARD: "admin",
    USERS: "admin/users",
    COURSES: "admin/courses",
    CREATE_COURSE: "admin/courses/create",
    ENROLLMENTS: "admin/enrollments",
  },
  INSTRUCTOR: {
    DASHBOARD: "instructor",
    COURSES: "instructor/courses",
    CREATE_COURSE: "instructor/courses/create",
    STUDENTS: "instructor/students",
    UPLOAD: "instructor/upload",
  },
};
